# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PyCon CZ 2016' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PyCon CZ 2016
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'TwitterCore'
  pod 'SVProgressHUD'
end
